apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-queue

spec:
  # this defines which pods represented by the service
  selector:
    app: fleetman-queue
    release: "1"

  ports:
    - name: http
      port: 8161
      nodePort: 30010
  
  type: NodePort
