apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-queue

spec:
  # this defines which pods represented by the service
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-position-tracker

spec:
  # this defines which pods represented by the service
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080
      #nodePort: 30020 # enable this to make this service visible outside k8s cluster
  
  #type: NodePort # enable this to make this service visible outside k8s cluster
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-api-gateway

spec:
  # this defines which pods represented by the service
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-webapp

spec:
  # this defines which pods represented by the service
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080
  
  type: NodePort
