apiVersion: v1
kind: Service
metadata:
  # unique key of the service instance
  name: fleetman-webapp

spec:
  # this defines which pods represented by the service
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080
  
  type: NodePort
